### Тема “Вычисления с помощью Numpy”

#### Задание 1

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

#### Задание 2

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание 3

In [7]:
b = a_centered[0:, 0]
b

array([-1.,  0.,  1.,  1., -1.])

In [8]:
c = a_centered[0:, 1]
c

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [9]:
a_centered_sp = np.dot(b, c)
a_centered_sp

8.0

In [10]:
N = len(a[:])
N

5

In [11]:
cov = a_centered_sp / (N - 1)
cov

2.0

#### Задание 4

In [12]:
a_transpose = np.transpose(a)
a_transpose

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [13]:
COV = np.cov(a_transpose)
COV

array([[1. , 2. ],
       [2. , 4.3]])

In [14]:
cov = COV[0, 1]
cov

2.0

### Тема “Работа с данными в Pandas”

#### Задание 1

In [16]:
import pandas as pd

In [18]:
authors = pd.DataFrame({'author_id': [1, 2, 3],
                        'author_name':['Тургенев', 'Чехов', 'Островский']}, columns = ['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [21]:
book = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3], 
                     'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price': [450, 300, 350, 500, 450, 370, 290]}, columns = ['author_id', 'book_title', 'price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

#### Задание 2

In [32]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

#### Задание 3

In [33]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

#### Задание 4

In [42]:
authors_stat = authors_price.groupby("author_name")
authors_price.agg({"price": "max", "price": "min", "price": "mean"})

price    387.142857
dtype: float64